name: Linting and testing

# Test django-star-ratings on:
#   all supported Django and Python versions

on:
  push:
  pull_request:

jobs:
  lint:
    name: Lint and format

    runs-on: ubuntu-latest

    env:
      # Choose a version of Python in which to set up the tox test environment.
      python-version: 3.9
      linted-dirs: src tests
      # TODO: also lint demo once once formatting issues have been fixed.
      #linted-dirs: demo src tests

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ env.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ env.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install black flake8 isort
    - name: Run lints
      run: |
        flake8 ${{ env.linted-dirs }}
        black --check ${{ env.linted-dirs }}
        isort --check ${{ env.linted-dirs }}
  test:
    name: Unit tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.6"
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox tox-gh-actions
    - name: Test with tox
      run: tox
